#aqui é o meu ponto de entrada para o projeto 

from utils import ler_lista_numeros
# o que isso aqui significa?
#R->'VA ATE O ARQUIVO UTILS.PY E TRAGA PARA CA A FUNCAO LER_LISTA_NUMEROS
#AQUI EU TOU DIZENDO QUE EU SOU TOU PEGANDO A FUNCAO LER_LISTA_NUMEROS DO ARQUIVO UTILS
#EU QUERO USAR ESSA FERRAMENTA QUE ESTA GUARDADA NAQUELE ARQUIVO




def main():
    #FUNCAO PRINCIPAL DO PROGRAMA
    #EM PROJETOS PROFISSIONAIS SEMPRE EXISTE UMA FUNCAO CHAMADA MAIN()
    #SERVE COMO UM PONTO DE PARTIDA ORGANIZADO


    valores = ler_lista_numeros()
    #TA CHAMANDO A FUNCAO QUE VEIO LA DO UTILS.PY
    #ESSA FUNCAO ELA JA FOI ESTRUTURADA PARA O QUE ELA DEVE FAZER

    #PERGUNTA VALORES AO USUARIO//VALIDA//CORRIGE//CONVERTE//RETORNA UMA LISTA DE NUMEROS
    #O RESULTADO DE TUDO QUE ESSA FUNCAO FAZ, ELA FICA DENTRO DA VARAIVEL VALORES

    # UTILS.PY->EXECUTA A FUNCAO
    #MAIN.PY->RECEBE O RESULTADO
    print("Valores digitados:", valores)
    #SIMPLESMENTE, EXIBE O QUE A FUNCAO RETORNOU 
if __name__ == "__main__":
    main()#SE O ARQUIVO TA SENDO EXECUTADO DIRETAMENTO(O CASO AO RODAR PYTHON MAIN.PY), ENTAO CHAMA A FUNCAO PRINCIPAL

    

#PARTE MAIS IMPORTANTE PROFISSIONALMENTE 
#ELA VERIFICA SE ESSE ARQUIVO ESTA SENDO EXECUTADO DIRETAMENTE
#SE SIM, RODA A FUNCAO MAIN()
#SE NAO , NAO RODA
